name: Release

on:
  push:
    tags:
      - 'v*'

env:
  BUNDLE_FILENAME: ${{ github.event.repository.name }}.zip

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Create the bundle
        run: zip $BUNDLE_FILENAME *.FCStd
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="Version ${tag#v}" \
              --generate-notes \
              $BUNDLE_FILENAME
